disabled_rules:
  - function_parameter_count
  - nesting
  - identifier_name
  - trailing_comma
  - file_length
opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
line_length: 120
type_body_length:
  warning: 350
  error: 400
function_body_length:
  warning: 45
excluded:
  - Pods
reporter: "xcode"
warning_threshold: 15
