disabled_rules:
  - function_parameter_count
  - nesting
  - variable_name
  - trailing_comma
opt_in_rules:
  - empty_count
  - force_unwrapping
  - private_outlet
line_length: 120
type_body_length:
  warning: 300
  error: 400
excluded:
  - Pods
reporter: "xcode"
warning_threshold: 15
